[package]
name = "riscv_emu_web"
version = "0.1.0"
authors = ["Hidenori"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.69"
riscv_emu = {path = "../"}

[lib]
name = "riscv_emu_web"
path = "src/lib.rs"
crate-type = ["cdylib"]
